from tkinter import *
from PIL import ImageTk, Image
app = Tk()
app.geometry('400x200')
app.title('Registration Form')
def choose():
    new = Toplevel(app)
    new.geometry('600x700')
    new.title('Registration form')
    
    #logo = ImageTk.PhotoImage(Image.open("STCET logo.png"))
    #label = Label(image = logo).grid(ipadx=450)

    e1 = Label(new, text = 'ST. THOMAS\' COLLEGE OF ENGINEERING AND TECHNOLOGY', font=10)
    e1.grid(row=0,column=1)
    e2 = Label(new, text = '4, Diamond Harbour Road, Alipore Body Guard Lines, Alipore, Kolkata, West Bengal 700023') 
    e2.grid(row=1,column=1)
    e3 = Label(new, text = 'Contact No.: (+033)2448-1081')
    e3.grid(row=2,column=1)
    e4 = Label(new, text = 'Mail ID: stcet2000@gmail.com')
    e4.grid(row=3,column=1)
    e5 = Label(new, text = 'STUDENT REGISTRATION FROM ', fg='blue', font=13)
    e5.grid(row=4,column=1)
    
    label_name=Label(new,text="Name: ")
    entry_name=Entry(new,width=50,bd=2)
    label_email=Label(new,text="E-mail: ")
    entry_email=Entry(new,width=50,bd=2)
    label_phn=Label(new,text="Phone No.: ")
    entry_phn=Entry(new,width=50,bd=2)
    label_present_add=Label(new,text="Present Address: ")
    entry_present_add=Entry(new,width=50,bd=2)
    label_per_add=Label(new,text="Permanent Address: ")
    entry_per_add=Entry(new,width=50,bd=2)
    label_gender=Label(new,text="Gender: ")
    f = Frame(new)
    f.grid(row=11,column = 1)
    var=IntVar()
    r1=Radiobutton(f,text="Male",padx= 10, variable= var, value=1)
    r1.pack(side=LEFT)
    r2=Radiobutton(f,text="Female",padx= 50, variable= var, value=2)
    r2.pack(side = LEFT)
    r3=Radiobutton(f,text="Other",padx= 10, variable= var, value=3)
    r3.pack(side=LEFT)
    label_fat_name=Label(new,text="Father's Name: ")
    entry_fat_name=Entry(new,width=50,bd=2)
    label_mot_name=Label(new,text="Mother's Name: ")
    entry_mot_name=Entry(new,width=50,bd=2)
    label_fat_phn=Label(new,text="Father's Phone No.: ")
    entry_fat_phn=Entry(new,width=50,bd=2)
    label_mot_phn=Label(new,text="Mother's Phone No.: ")
    entry_mot_phn=Entry(new,width=50,bd=2)
    label_class_10=Label(new,text="Class X",font=("Verdana",12,"bold"))
    label_total_10=Label(new,text="Total Score: ")
    entry_total_10=Entry(new,width=50,bd=2)
    label_percent_10=Label(new,text="Percentage: ")
    entry_percent_10=Entry(new,width=50,bd=2)
    label_board_10=Label(new,text="Board: ")
    label_class_12=Label(new,text="Class XII",font=("Verdana",12,"bold"))
    label_total_12=Label(new,text="Total Score: ")
    entry_total_12=Entry(new,width=50,bd=2)
    label_percent_12=Label(new,text="Percentage: ")
    entry_percent_12=Entry(new,width=50,bd=2)
    label_board_12=Label(new,text="Board: ")
    
    #canvas = Canvas(new,bd = 3, relief = 'groove')
    #canvas.pack()
    
    label_name.grid(row=6,column=0,pady=30)
    label_email.grid(row=7,column=0)
    label_phn.grid(row=8,column=0,pady=30)
    label_present_add.grid(row=9,column=0)
    label_per_add.grid(row=10,column=0,pady=30)
    label_gender.grid(row=11,column=0)
    label_fat_name.grid(row=12,column=0,pady=30)
    label_mot_name.grid(row=13,column=0)
    label_fat_phn.grid(row=14,column=0)
    label_mot_phn.grid(row=15,column=0)
    label_class_10.grid(row=16,column=0,pady=30)
    label_total_10.grid(row=17,column=0)
    label_percent_10.grid(row=18,column=0,pady=30)
    label_board_10.grid(row=19,column=0,pady=30)
    label_class_12.grid(row=20,column=0)
    label_total_12.grid(row=21,column=0)
    label_percent_12.grid(row=22,column=0)
    label_board_12.grid(row=23,column=0,pady=30)
    
    
    entry_name.grid(row=6,column=1)
    entry_email.grid(row=7,column=1)
    entry_phn.grid(row=8,column=1)
    entry_present_add.grid(row=9,column=1)
    entry_per_add.grid(row=10,column=1)
    entry_fat_name.grid(row=12,column=1,pady=30)
    entry_mot_name.grid(row=13,column=1)
    entry_fat_phn.grid(row=14,column=1,pady=30)
    entry_mot_phn.grid(row=15,column=1)
    entry_total_10.grid(row=17,column=1)
    entry_percent_10.grid(row=18,column=1)
    entry_total_12.grid(row=21,column=1,pady=30)
    entry_percent_12.grid(row=22,column=1)
    
l1=Frame(app,bg="red")
l1.pack()
label=Label(l1,text='Welcome',font=('Arial',30))
label.pack()
b1=Frame(app,bg="blue",borderwidth=2,)
b1.place(x=50,y=100)
button1 = Button(b1,text='Start Registration',font = ('Arial',15),command=choose,activebackground='blue',activeforeground='white')
button1.pack()
b2=Frame(app,bg="blue",borderwidth=2)
b2.place(x=270,y=100)
button2 = Button(b2,text='Exit',command = app.destroy,font = ('Arial',15),activebackground='blue',activeforeground='white')
button2.pack()
app.mainloop()