    f = Frame(new)
    f.grid(row=11,column = 1)
    var=IntVar()
    r1=Radiobutton(f,text="Male",padx= 10, variable= var, value=1)
    r1.pack(side=LEFT)
    r2=Radiobutton(f,text="Female",padx= 50, variable= var, value=2)
    r2.pack(side = LEFT)
    r3=Radiobutton(f,text="Other",padx= 10, variable= var, value=3)
    r3.pack(side=LEFT)